CREATE TABLE IF NOT EXISTS users (
  login TEXT NOT NULL PRIMARY KEY UNIQUE, 
  name TEXT NOT NULL, 
  pass TEXT NOT NULL,
  invite TEXT
);

CREATE TABLE IF NOT EXISTS invites (
  value TEXT NOT NULL PRIMARY KEY UNIQUE,
  isActive BOOLEAN NOT NULL
);